name: daily
on:
  push:
    branches:
      - updater
  schedule:
    - cron: '0 1 * * *' # once per day
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Setup pipenv virtual environment
        run: |
          pip install pipenv
          pipenv install --skip-lock

      - name: Clone pvme-guides repository
        run: git clone --depth 1 https://github.com/pvme/pvme-guides.git

      - name: update pvme-spreadsheet
        run: pipenv run python pvme_spreadsheet.py
